/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Elisete
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        Menu = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        fabricanteMenu = new javax.swing.JMenuItem();
        produtoMenu = new javax.swing.JMenuItem();
        cadastroAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Drogaria");

        cadastroMenu.setText("Arquivo");

        fabricanteMenu.setText("Fabricante");
        fabricanteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricanteMenuActionPerformed(evt);
            }
        });
        cadastroMenu.add(fabricanteMenu);

        produtoMenu.setText("Produto");
        produtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoMenuActionPerformed(evt);
            }
        });
        cadastroMenu.add(produtoMenu);

        Menu.add(cadastroMenu);

        cadastroAjuda.setText("Editar");

        menuSobre.setText("Sobre");
        cadastroAjuda.add(menuSobre);

        Menu.add(cadastroAjuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoMenuActionPerformed

    private void fabricanteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricanteMenuActionPerformed
        FormFabricante fab = new FormFabricante(this,true); // fica no modal, a segunda janela, nao pode clicar na primeira.
        fab.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // Evita que clique no x e saia da operaçao
        fab.setTitle("Administração de Fabricantes"); //Nome da janela
        fab.setLocationRelativeTo(null); // Fica no centro da tela o layout
        fab.setResizable(false); //Impede que aumente a tela
        fab.setVisible(true);
        
    }//GEN-LAST:event_fabricanteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu cadastroAjuda;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem fabricanteMenu;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem produtoMenu;
    // End of variables declaration//GEN-END:variables
}
